transaction_info_btn = "//*[@id=\"mega\"]/ul/li[2]/a"
stock_price_and_mothly_btn = "//*[@id=\"mega\"]/ul/li[2]/div/div/ul[1]/li[10]/a"
year_112_selector_option = "//*[@id=\"label0\"]/option[2]"
month_selector = "//*[@id=\"form\"]/div/div[1]/div[1]/span/select[2]/option[1]"
stock_number_input = "//*[@id=\"label1\"]"
search_btn = "//*[@id=\"form\"]/div/div[1]/div[3]/button"
table = "//*[@id=\"reports\"]/div[2]/div[2]/table/tbody/tr"
table_content = "//*[@id=\"reports\"]/div[2]/div[2]/table/tbody/tr[{i}]/td[2]"